package model

type SportType string

const (
	SportTypeAlpineSki                     SportType = "AlpineSki"
	SportTypeBackcountrySki                SportType = "BackcountrySki"
	SportTypeBadminton                     SportType = "Badminton"
	SportTypeCanoeing                      SportType = "Canoeing"
	SportTypeCrossfit                      SportType = "Crossfit"
	SportTypeEBikeRide                     SportType = "EBikeRide"
	SportTypeElliptical                    SportType = "Elliptical"
	SportTypeEMountainBikeRide             SportType = "EMountainBikeRide"
	SportTypeGolf                          SportType = "Golf"
	SportTypeGravelRide                    SportType = "GravelRide"
	SportTypeHandcycle                     SportType = "Handcycle"
	SportTypeHighIntensityIntervalTraining SportType = "HighIntensityIntervalTraining"
	SportTypeHike                          SportType = "Hike"
	SportTypeIceSkate                      SportType = "IceSkate"
	SportTypeInlineSkate                   SportType = "InlineSkate"
	SportTypeKayaking                      SportType = "Kayaking"
	SportTypeKitesurf                      SportType = "Kitesurf"
	SportTypeMountainBikeRide              SportType = "MountainBikeRide"
	SportTypeNordicSki                     SportType = "NordicSki"
	SportTypePickleball                    SportType = "Pickleball"
	SportTypePilates                       SportType = "Pilates"
	SportTypeRacquetball                   SportType = "Racquetball"
	SportTypeRide                          SportType = "Ride"
	SportTypeRockClimbing                  SportType = "RockClimbing"
	SportTypeRollerSki                     SportType = "RollerSki"
	SportTypeRowing                        SportType = "Rowing"
	SportTypeRun                           SportType = "Run"
	SportTypeSail                          SportType = "Sail"
	SportTypeSkateboard                    SportType = "Skateboard"
	SportTypeSnowboard                     SportType = "Snowboard"
	SportTypeSnowshoe                      SportType = "Snowshoe"
	SportTypeSoccer                        SportType = "Soccer"
	SportTypeSquash                        SportType = "Squash"
	SportTypeStairStepper                  SportType = "StairStepper"
	SportTypeStandUpPaddling               SportType = "StandUpPaddling"
	SportTypeSurfing                       SportType = "Surfing"
	SportTypeSwim                          SportType = "Swim"
	SportTypeTableTennis                   SportType = "TableTennis"
	SportTypeTennis                        SportType = "Tennis"
	SportTypeTrailRun                      SportType = "TrailRun"
	SportTypeVelomobile                    SportType = "Velomobile"
	SportTypeVirtualRide                   SportType = "VirtualRide"
	SportTypeVirtualRow                    SportType = "VirtualRow"
	SportTypeVirtualRun                    SportType = "VirtualRun"
	SportTypeWalk                          SportType = "Walk"
	SportTypeWeightTraining                SportType = "WeightTraining"
	SportTypeWheelchair                    SportType = "Wheelchair"
	SportTypeWindsurf                      SportType = "Windsurf"
	SportTypeWorkout                       SportType = "Workout"
	SportTypeYoga                          SportType = "Yoga"
)
